### ISSUE TITLE
Cannot read property 'MongoID' problem

### ISSUE THREAD

**Issue by elmor34** [idanwe/ionic-cli-meteor-whatsapp-tutorial#2]
I selected option 4 from list . But I still get the error below.
regards
Gokhan AYKAN

Unable to find a suitable version for angular, please choose one:
    1) angular#1.4.3 which resolved to 1.4.3 and is required by angular-animate#1.4.3, angular-sanitize#1.4.3, ionic#1.1.0
    2) angular#>=1.2.0 <1.5.0 which resolved to 1.4.3 and is required by angular-moment#0.10.3
    3) angular#>= 1.0.8 which resolved to 1.4.3 and is required by angular-ui-router#0.2.13
    4) angular#1.4.4 which resolved to 1.4.4 and is required by angular-meteor#1.0.2

*_ERROR : *_

*
Uncaught TypeError: **Cannot read property 'MongoID' of undefined**(anonymous function) @ angular-meteor.bundle.js:17(anonymous function) @ angular-meteor.bundle.js:392
ionic.bundle.js:8895 
*
*
Uncaught Error: [$injector:modulerr] Failed to instantiate module whatsapp due to:
Error: [$injector:modulerr] Failed to instantiate module angular-meteor due to:
Error: [$injector:nomod] Module 'angular-meteor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.3/$injector/nomod?p0=angular-meteor
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8895:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:10785:17
    at ensure (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10709:38)
    at module (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10783:14)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13189:22
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9163:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13173:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13190:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9163:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13173:5)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=angular-meteor&p1=E…%3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A13173%3A5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:8895:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13212:15
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9163:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13173:5)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:13190:40
    at forEach (http://localhost:8100/lib/ionic/js/ionic.bundle.js:9163:20)
    at loadModules (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13173:5)
    at createInjector (http://localhost:8100/lib/ionic/js/ionic.bundle.js:13099:11)
    at doBootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10457:20)
    at bootstrap (http://localhost:8100/lib/ionic/js/ionic.bundle.js:10478:12)
http://errors.angularjs.org/1.4.3/$injector/modulerr?p0=whatsapp&p1=Error%3…3A%2F%2Flocalhost%3A8100%2Flib%2Fionic%2Fjs%2Fionic.bundle.js%3A10478%3A12)(anonymous function) @ ionic.bundle.js:8895(anonymous function) @ ionic.bundle.js:13212forEach @ ionic.bundle.js:9163loadModules @ ionic.bundle.js:13173createInjector @ ionic.bundle.js:13099doBootstrap @ ionic.bundle.js:10457bootstrap @ ionic.bundle.js:10478angularInit @ ionic.bundle.js:10372(anonymous function) @ ionic.bundle.js:37186trigger @ ionic.bundle.js:11823eventHandler @ ionic.bundle.js:12098
*

**Comment by idanwe** [comment]
Yes is problem with the bundle of angular-meteor, it fixed with this PR Urigo/angular-meteor#783.

@Urigo will publish new version and it will be solved

**Comment by elmor34** [comment]
Thanks

**Comment by idanwe** [comment]
@elmor34 @Urigo released 1.0.3 and now it fixed
